name: Deploy with DockerHub to Ubuntu Server

on:
  push:
    branches:
      - main  # main 브랜치에 푸시될 때 트리거

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 코드 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # JDK 21 설정
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # gradlew 권한 설정
      - name: Set gradlew permissions
        run: |
          chmod +x ./gradlew

      - name: Create application.yml
        shell: bash
        run: |
          mkdir -p src/main/resources
          cat << 'EOF' > src/main/resources/application.yml 
          ${{ secrets.APPLICATION_YML }}
          EOF

      # Gradle 캐시 추가 (빌드 속도 개선)
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: gradle-${{ runner.os }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # gradle 빌드
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # docker 로그인 
      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # docker build : image를 생성 => dockerhub에 전송  
      - name: Build and Push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/spring-my-app:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/spring-my-app:latest

      # 개인키를 가지고 AWS에 접속(ssh-agent 최신 버전)
      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SERVER_SSH_KEY }}

      # 등록 => 서버키가 등록 
      - name: Add known_hosts
        run: |
          ssh-keyscan -H ed25519 43.203.118.115 >> ~/.ssh/known_hosts

      # container 실행
      - name: Deploy on server using DockerHub image
        run: |
          ssh ubuntu@43.203.118.115 << 'EOF'
            docker stop spring-my-app || true
            docker rm spring-my-app || true
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/spring-my-app:latest
            docker run -d --name spring-my-app -p 9090:9090 ${{ secrets.DOCKERHUB_USERNAME }}/spring-my-app:latest
          EOF
